# Page settings

baseurl = "https://tmp.ike.id.au/"
languageCode = "en-au"
title = "Ike Johnson-Woods"
theme = "orbit"
googleAnalytics = "UA-209060765-1"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Ike Johnson-Woods - CV"
    author = "Ike Johnson-Woods"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "main.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Ike Johnson-Woods"
        tagline = "Theatre Technician"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:contact@ike.id.au"
        title = "contact@ike.id.au"

#        [[params.contact.list]]
#        class = "phone"
#        icon = "fa-phone"
#        url = "tel:+61457036942"
#        title = "+61 457 036 942"

        [[params.contact.list]]
        class = "instagram"
        icon = "fa-instagram"
        url = "https://instagram.com/NotActuallyTerry"
        title = "@NotActuallyTerry"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "https://github.com/NotActuallyTerry"
        title = "@NotActuallyTerry"

    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Bachelor of Performing Arts"
        college = "WA Academy of Performing Arts"
        dates = "2021 - Current"

    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Photography"

        [[params.interests.list]]
        interest = "Volunteering"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Technical Director"
        dates = "2020 - Present"
        company = "Northam Theatre Group"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

        [[params.jobs.list]]
        position = "Theatre Technician"
        dates = "2018 - Present"
        company = "Link Theatre, Northam"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.jobs.list]]
        position = "Volunteer Ambulance Officer"
        dates = "2020 - Present"
        company = "St John WA"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Love Tropics"
        url = "https://lovetropics.org/"
        tagline = "Love Tropics is a Weekend-long livestream hosted in Minecraft. Initially focused on assisting Puerto Rico in the aftermath of Hurricane Maria, we now raise money for various climate change-related causes. To date, we have raised US$156,119 for 4 causes."

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

    # Skills section
    [params.skills]
        enable = false
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python & Django"
        level = "98%"
                
    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
